POPULAR_STOCKS = [
    {"symbol": "AAPL", "name": "Apple Inc."},
    {"symbol": "MSFT", "name": "Microsoft Corporation"},
    {"symbol": "NVDA", "name": "NVIDIA Corporation"},
    {"symbol": "AMZN", "name": "Amazon.com Inc."},
    {"symbol": "GOOGL", "name": "Alphabet Inc."},
    {"symbol": "META", "name": "Meta Platforms Inc."},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc."},
    {"symbol": "TSLA", "name": "Tesla Inc."},
    {"symbol": "AVGO", "name": "Broadcom Inc."},
    {"symbol": "LLY", "name": "Eli Lilly and Company"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co."},
    {"symbol": "WMT", "name": "Walmart Inc."},
    {"symbol": "V", "name": "Visa Inc."},
    {"symbol": "MA", "name": "Mastercard Incorporated"},
    {"symbol": "XOM", "name": "Exxon Mobil Corporation"},
    {"symbol": "UNH", "name": "UnitedHealth Group Incorporated"},
    {"symbol": "ORCL", "name": "Oracle Corporation"},
    {"symbol": "COST", "name": "Costco Wholesale Corporation"},
    {"symbol": "HD", "name": "The Home Depot Inc."},
    {"symbol": "PG", "name": "The Procter & Gamble Company"},
    {"symbol": "NFLX", "name": "Netflix Inc."},
    {"symbol": "JNJ", "name": "Johnson & Johnson"},
    {"symbol": "BAC", "name": "Bank of America Corporation"},
    {"symbol": "ABBV", "name": "AbbVie Inc."},
    {"symbol": "KO", "name": "The Coca-Cola Company"},
    {"symbol": "PLTR", "name": "Palantir Technologies Inc."},
    {"symbol": "CRM", "name": "Salesforce Inc."},
    {"symbol": "AMD", "name": "Advanced Micro Devices Inc."},
    {"symbol": "CVX", "name": "Chevron Corporation"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc."},
    {"symbol": "IBM", "name": "International Business Machines Corporation"},
    {"symbol": "WFC", "name": "Wells Fargo & Company"},
    {"symbol": "GE", "name": "GE Aerospace"},
    {"symbol": "MRK", "name": "Merck & Co. Inc."},
    {"symbol": "PM", "name": "Philip Morris International Inc."},
    {"symbol": "MCD", "name": "McDonald's Corporation"},
    {"symbol": "ABT", "name": "Abbott Laboratories"},
    {"symbol": "LIN", "name": "Linde plc"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc."},
    {"symbol": "DIS", "name": "The Walt Disney Company"},
    {"symbol": "GS", "name": "The Goldman Sachs Group Inc."},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc."},
    {"symbol": "NOW", "name": "ServiceNow Inc."},
    {"symbol": "ACN", "name": "Accenture plc"},
    {"symbol": "RTX", "name": "RTX Corporation"},
    {"symbol": "ADBE", "name": "Adobe Inc."},
    {"symbol": "QCOM", "name": "QUALCOMM Incorporated"},
    {"symbol": "CAT", "name": "Caterpillar Inc."},
    {"symbol": "TXN", "name": "Texas Instruments Incorporated"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc."},
    {"symbol": "VZ", "name": "Verizon Communications Inc."},
    {"symbol": "PEP", "name": "PepsiCo Inc."},
    {"symbol": "SPGI", "name": "S&P Global Inc."},
    {"symbol": "AMGN", "name": "Amgen Inc."},
    {"symbol": "UBER", "name": "Uber Technologies Inc."},
    {"symbol": "NEE", "name": "NextEra Energy Inc."},
    {"symbol": "HON", "name": "Honeywell International Inc."},
    {"symbol": "LOW", "name": "Lowe's Companies Inc."},
    {"symbol": "PFE", "name": "Pfizer Inc."},
    {"symbol": "C", "name": "Citigroup Inc."},
    {"symbol": "DHR", "name": "Danaher Corporation"},
    {"symbol": "UNP", "name": "Union Pacific Corporation"},
    {"symbol": "T", "name": "AT&T Inc."},
    {"symbol": "BLK", "name": "BlackRock Inc."},
    {"symbol": "SYK", "name": "Stryker Corporation"},
    {"symbol": "GILD", "name": "Gilead Sciences Inc."},
    {"symbol": "ETN", "name": "Eaton Corporation plc"},
    {"symbol": "SCHW", "name": "The Charles Schwab Corporation"},
    {"symbol": "TJX", "name": "The TJX Companies Inc."},
    {"symbol": "DE", "name": "Deere & Company"},
    {"symbol": "BSX", "name": "Boston Scientific Corporation"},
    {"symbol": "PANW", "name": "Palo Alto Networks Inc."},
    {"symbol": "ADP", "name": "Automatic Data Processing Inc."},
    {"symbol": "NKE", "name": "NIKE Inc."},
    {"symbol": "LMT", "name": "Lockheed Martin Corporation"},
    {"symbol": "COP", "name": "ConocoPhillips"},
    {"symbol": "CB", "name": "Chubb Limited"},
    {"symbol": "MDT", "name": "Medtronic plc"},
    {"symbol": "BMY", "name": "Bristol Myers Squibb Company"},
    {"symbol": "AMAT", "name": "Applied Materials Inc."},
    {"symbol": "ANET", "name": "Arista Networks Inc."},
    {"symbol": "MU", "name": "Micron Technology Inc."},
    {"symbol": "SBUX", "name": "Starbucks Corporation"},
    {"symbol": "KLAC", "name": "KLA Corporation"},
    {"symbol": "UPS", "name": "United Parcel Service Inc."},
    {"symbol": "PLD", "name": "Prologis Inc."},
    {"symbol": "SO", "name": "The Southern Company"},
    {"symbol": "ICE", "name": "Intercontinental Exchange Inc."},
    {"symbol": "SHW", "name": "The Sherwin-Williams Company"},
    {"symbol": "MO", "name": "Altria Group Inc."},
    {"symbol": "ELV", "name": "Elevance Health Inc."},
    {"symbol": "CME", "name": "CME Group Inc."},
    {"symbol": "WM", "name": "Waste Management Inc."},
    {"symbol": "HCA", "name": "HCA Healthcare Inc."},
    {"symbol": "MCO", "name": "Moody's Corporation"},
    {"symbol": "APH", "name": "Amphenol Corporation"},
    {"symbol": "PH", "name": "Parker-Hannifin Corporation"},
    {"symbol": "EQIX", "name": "Equinix Inc."},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals Inc."},
    {"symbol": "AON", "name": "Aon plc"},
]
